import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [resultState, setResultState] = useState("initial value");

  const handleGetResult = async (): Promise<void> => {
    let response: Response | undefined;
    try {
      response = await fetch("/mocked/path");
    } catch (err) {
      if (err instanceof Error) {
        console.error(err.message);
      } else if (typeof err === "string") {
        console.error(err);
      } else {
        throw err;
      }
    }
    if (response instanceof Response) {
      const responseJson = response.json();
      const responseString = JSON.stringify(responseJson);
      setResultState(responseString);
    } else {
      throw new TypeError(`wtf:\n${JSON.stringify(response)}`);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Get Your Result</h2>
            <button
              type="button"
              onClick={handleGetResult}
              className={styles.button}
            >
              Get Result
            </button>
            <code className={styles.code}>{resultState}</code>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
