import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [resultState, setResultState] = useState("initial result");
  const [inputState, setInputState] = useState("initial input...");

  const [haveMadeCall, setHaveMadeCall] = useState(false);
  const [inputSuccess, setInputSuccess] = useState(false);

  const handleSubmitInput = async (): Promise<void> => {
    setHaveMadeCall(false);

    let response: Response | undefined;
    try {
      response = await fetch("/send/user/input", {
        method: "POST",
        body: JSON.stringify(inputState),
      });
    } catch (err) {
      setHaveMadeCall(true);
      setInputSuccess(false);
      if (err instanceof Error) {
        console.error(err.message);
      } else if (typeof err === "string") {
        console.error(err);
      } else {
        throw err;
      }
    }
    setHaveMadeCall(true);
    if (response instanceof Response) {
      setInputSuccess(response.ok);
    } else {
      setInputSuccess(false);
      throw new TypeError(`wtf:\n${JSON.stringify(response)}`);
    }
  };

  const handleGetResult = async (): Promise<void> => {
    let response: Response | undefined;
    try {
      response = await fetch("/execute/user/input");
    } catch (err) {
      if (err instanceof Error) {
        console.error(err.message);
      } else if (typeof err === "string") {
        console.error(err);
      } else {
        throw err;
      }
    }
    if (response instanceof Response) {
      const responseJson = await response.json();
      const responseString = JSON.stringify(responseJson);
      setResultState(responseString);
    } else {
      throw new TypeError(`wtf:\n${JSON.stringify(response)}`);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <form
              onSubmit={(ev) => {
                ev.preventDefault();
                handleSubmitInput();
              }}
            >
              <label htmlFor="user-input">
                <h2>Input Something</h2>
              </label>
              <input
                id="story"
                name="user-input"
                value={inputState}
                onChange={(ev) => {
                  setInputState(ev.target.value);
                }}
                className={styles.input}
              ></input>
              <button type="submit" className={styles.button}>
                Set Input
              </button>
            </form>
            {haveMadeCall && (
              <p>{inputSuccess ? "Success!" : "Error, see console"}</p>
            )}
          </div>
          <div className={styles.card}>
            <h2>Get Your Result</h2>
            <button
              type="button"
              onClick={handleGetResult}
              className={styles.button}
            >
              Get Result
            </button>
            <p className={styles.result}>{resultState}</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
