import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

const EXTRACTION_KEY_KEY = "extractionKey";

export default function Home() {
  const [resultState, setResultState] = useState("initial result");
  const [serverCode, setServerCode] = useState(
    `
console.log("server-side code running");

return {
  tree1: "apple",
  tree2: "nitrogen-fixer", 
}
  `.trim()
  );
  const [clientCode, setClientCode] = useState(`
{extractionKey: "tree2"}
  `);

  const [haveMadeCall, setHaveMadeCall] = useState(false);
  const [inputSuccess, setInputSuccess] = useState(false);

  const handleSubmitInput = async (): Promise<void> => {
    setHaveMadeCall(false);

    let response: Response | undefined;
    try {
      response = await fetch("/server/update", {
        method: "POST",
        body: JSON.stringify(serverCode),
      });
    } catch (err) {
      setHaveMadeCall(true);
      setInputSuccess(false);
      if (err instanceof Error) {
        console.error(err.message);
      } else if (typeof err === "string") {
        console.error(err);
      } else {
        throw err;
      }
    }
    setHaveMadeCall(true);
    if (response instanceof Response) {
      setInputSuccess(response.ok);
    } else {
      setInputSuccess(false);
      throw new TypeError(`wtf:\n${JSON.stringify(response)}`);
    }
  };

  const handleGetResult = async (configString: string): Promise<void> => {
    let config;
    try {
      config = Function(`const config = ${configString}; return config;`)();
    } catch (err) {
      console.error(err);
    }

    // DEBUG
    console.log("client side");
    console.log(config);

    const extractionKey: string = config[EXTRACTION_KEY_KEY];
    if (!extractionKey) {
      throw new TypeError(
        "Please make sure you specify and '{extractionKey: ...}'"
      );
    }

    let response: Response | undefined;
    const urlString = `/server/execute?extractionKey=${encodeURIComponent(
      extractionKey
    )}`;
    try {
      response = await fetch(urlString);
    } catch (err) {
      if (err instanceof Error) {
        console.error(err.message);
      } else if (typeof err === "string") {
        console.error(err);
      } else {
        throw err;
      }
    }
    if (response instanceof Response) {
      const responseJson = await response.json();
      const responseString = JSON.stringify(responseJson);
      setResultState(responseString);
    } else {
      throw new TypeError(`wtf:\n${JSON.stringify(response)}`);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Fake server-side code execution</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Fake Server-Side Code Execution</h1>
        <p className={styles.description}>
          Edit the server side function body on the right (should return an
          object), edit the key extraction code on the right.
        </p>
        <div className={styles.grid}>
          <div className={styles.card}>
            <form
              onSubmit={(ev) => {
                ev.preventDefault();
                handleSubmitInput();
              }}
            >
              <label htmlFor="user-server-input">
                <h2>Server-Side Code</h2>
              </label>
              <textarea
                name="user-server-input"
                value={serverCode}
                onChange={(ev) => {
                  setServerCode(ev.target.value);
                }}
                className={styles.input}
                rows={5}
                cols={5}
              ></textarea>
              <button type="submit" className={styles.button}>
                Update Server
              </button>
            </form>
            {haveMadeCall && (
              <p>{inputSuccess ? "Server updated" : "Error, see console"}</p>
            )}
          </div>
          <div className={styles.card}>
            <label htmlFor="user-client-input">
              <h2>Client-Side Code</h2>
            </label>
            <textarea
              name="user-client-input"
              value={clientCode}
              onChange={(ev) => {
                setClientCode(ev.target.value);
              }}
              className={styles.input}
              rows={5}
              cols={5}
            ></textarea>
            <button
              type="button"
              onClick={() => handleGetResult(clientCode)}
              className={styles.button}
            >
              Execute Client Code
            </button>
          </div>
        </div>
        <div className={styles.grid}>
          <div className={styles.card + " " + styles.bigCard}>
            <h2>Client Side Result</h2>
            <p className={styles.result}>{resultState}</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
